# Generated by Django 3.2.8 on 2022-02-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20220217_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nasc',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
